name: PHP CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run PHPUnit tests
        run: |
          if [ -f vendor/bin/phpunit ]; then
            vendor/bin/phpunit
          else
            echo "PHPUnit not found. Skipping tests."
          fi

      - name: Deploy to server via SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private.key
          chmod 600 private.key
          ssh -o StrictHostKeyChecking=no -i private.key ubuntu@44.204.59.63 << 'EOF'
            cd /var/www/html/php-site/airplane-seating-system
            git pull origin main
            sudo systemctl restart apache2
          EOF
          rm private.key
